### ISSUE TITLE
allow single quote when add or update Snippets - real_escape_string

### ISSUE THREAD

**Issue by SomwangShep** [MCLACS/CSCI452-FA18-Public#113]

**Comment by dralvord** [comment]
I found that the issue was actually because the html needed the escape not the database.

**Comment by SomwangShep** [comment]
Awesome, I did spend hour in PHP trying to use real_escape_string but it not working. Which part did you change?

**Comment by dralvord** [comment]
I added htmlspecialchars() to each part of the return in the filter
